<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <NoWarn>$(NoWarn);CS0618;CA1801;CA1812;CA1816;CA1062;CA1063;CS8767;CS8602;CS8618;IDE1006</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicData\DynamicData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.console" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Reactive.Testing" />
    <PackageReference Include="PublicApiGenerator" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
