<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net462;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="DynamicData.Cache" />
    <Using Include="DynamicData.Cache.Internal" />
    <Using Include="DynamicData.Diagnostics" />
    <Using Include="DynamicData.Internal" />
    <Using Include="DynamicData.List.Internal" />
    <Using Include="DynamicData.List.Linq" />
    <Using Include="DynamicData.Operators" />
    <Using Include="System.Collections" />
    <Using Include="System.Collections.Concurrent" />
    <Using Include="System.Collections.Specialized" />
    <Using Include="System.Diagnostics" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="System.Linq.Expressions" />
    <Using Include="System.Numerics" />
    <Using Include="System.Reactive" />
    <Using Include="System.Reactive.Concurrency" />
    <Using Include="System.Reactive.Threading.Tasks" />
  </ItemGroup>

  <PropertyGroup>
    <Title>Dynamic Data</Title>
    <Description>
Bring the power of Rx to collections using Dynamic Data.
Dynamic Data is a comprehensive caching and data manipulation solution which introduces domain centric observable collections.
      Linq extensions enable dynamic filtering, sorting, grouping, transforms, binding, pagination, data virtualisation, expiration, disposal management plus more.
    </Description>
  </PropertyGroup>

  <!-- AsyncDisposeMany is only supported on platforms that have IAsyncDisposable. -->
  <ItemGroup Condition="!$(DefineConstants.Contains('SUPPORTS_ASYNC_DISPOSABLE'))">
    <Compile Remove="Cache\ObservableCacheEx.AsyncDisposeMany.cs" />
  </ItemGroup>

</Project>
